name: Artifacts

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    
jobs:
    upload:
        name: Upload Job
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Execute Shell Script
          run: ./ascii-script.sh

        - uses: actions/upload-artifact@v4
          with:
            name: dragon
            path: dragon.txt
    
    download:
        needs: upload
        name: Download Job
        runs-on: ubuntu-latest
        steps:

        - uses: actions/download-artifact@v4
          with:
            name: dragon
            path: dragon.txt

        - run: cat dragon.txt
        
        
            


